# Generated by Django 5.2.7 on 2025-11-05 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='메모 제목을 입력하세요', max_length=200, verbose_name='제목')),
                ('content', models.TextField(help_text='메모 내용을 입력하세요', verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memos', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '메모',
                'verbose_name_plural': '메모 목록',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='memos_memo_created_62414f_idx'), models.Index(fields=['author', '-created_at'], name='memos_memo_author__327a79_idx')],
            },
        ),
    ]
