# Generated by Django 5.2.7 on 2025-11-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='category',
            field=models.CharField(blank=True, choices=[('daily', '일상'), ('work', '업무'), ('personal', '개인')], help_text='메모의 범주를 선택하세요', max_length=20, null=True, verbose_name='범주'),
        ),
    ]
