# Generated by Django 5.2.7 on 2025-11-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0002_memo_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='category',
            field=models.CharField(blank=True, choices=[('daily', '일상'), ('work', '업무'), ('personal', '개인')], default='', help_text='메모의 범주를 선택하세요', max_length=20, verbose_name='범주'),
        ),
    ]
