# Generated by Django 5.2.7 on 2025-11-06 00:45

from django.db import migrations, models


def migrate_categories(apps, schema_editor):
    """기존 카테고리 데이터를 NULL로 변환"""
    Memo = apps.get_model('memos', 'Memo')
    # 기존 범주(daily, work, personal)를 모두 NULL로 변경
    Memo.objects.filter(category__in=['daily', 'work', 'personal']).update(category=None)
    # 빈 문자열도 NULL로 변경
    Memo.objects.filter(category='').update(category=None)


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0003_alter_memo_category'),
    ]

    operations = [
        migrations.RunPython(migrate_categories, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='memo',
            name='category',
            field=models.CharField(blank=True, choices=[('private', '개인'), ('public', '공개')], help_text='메모의 공개 범위를 선택하세요', max_length=20, null=True, verbose_name='범주'),
        ),
    ]
