# Generated by Django 4.2.28 on 2026-02-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', '공개'), ('private', '비공개')], default='public', max_length=10, verbose_name='공개 범주'),
        ),
    ]
