# Generated by Django 5.2.8 on 2025-11-11 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
    ]
