# Generated by Django 5.2.8 on 2025-11-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20251111_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', '공개'), ('private', '비공개')], default='public', max_length=10, verbose_name='공개 범주'),
        ),
    ]
