# Generated by Django 4.2.26 on 2025-11-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', '공개'), ('PRIVATE', '비공개')], default='PUBLIC', max_length=10, verbose_name='공개 범주'),
        ),
    ]
