# Generated by Django 4.2.27 on 2025-12-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('private', '비공개'), ('public', '공개')], default='public', max_length=10, verbose_name='공개 범주'),
        ),
    ]
